id: DE8A47009
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-02-24T10:29:27+00:00'
last_modified: '2022-05-27T05:59:52.242692+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f492:
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      order: 57
      base_file: f492.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
