id: P2A2A8243
initial_creation_type: ocr
source_metadata:
  volumes:
    c230b4bfa5ee450cb9c635fc9d0a4c43:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
